context:
  name: unfoldNd
  version: 0.2.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/unfoldnd-${{ version }}.tar.gz
  sha256: e8fdffeb68bc1b393ddc1b1c87056e0e4616db992e95c7dbc3dc90d564599397

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - pytorch
    - numpy

tests:
  - python:
      imports:
        - unfoldNd
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: N-dimensional unfold (im2col) and fold (col2im) in PyTorch
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/f-dangel/unfoldNd

extra:
  recipe-maintainers:
    - Tobias-Fischer
